service:
  host: '127.0.0.1'
  port: '8080'
  master: true
  slaves:
    - http://127.0.0.1:8080
    - http://127.0.0.1:8082

actions:
  - id: '8080_1'
    title: 'First'
    description: 'Test back'
    command: ["echo", "123321123321"]
  - id: '8080_2'
    title: 'Second'
    description: 'Test back'
    command: ["sh", "long_task.sh"]
